//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinFun.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaNotification))]


    public partial class Notification
    {
        public string NotiSerial { get; set; }
        public string InstanceId { get; set; }
        public string ToMemId { get; set; }
        public string NotiTitle { get; set; }
        public string NotifContent { get; set; }
        public System.DateTime timeReceived { get; set; }
        public bool readYet { get; set; }
        public bool keepNotice { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
