//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinFun.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    [MetadataType(typeof(Metavw_Activities))]
    public partial class vw_Activities
    {
        public string age { get; set; }
        public string actClassName { get; set; }
        public decimal Budget { get; set; }
        public string CountyName { get; set; }
        public string DistrictName { get; set; }
        public string gender { get; set; }
        public bool acceptDrop { get; set; }
        public string actClassId { get; set; }
        public short actCounty { get; set; }
        public System.DateTime actDeadline { get; set; }
        public string actDescription { get; set; }
        public short actDistrict { get; set; }
        public string actId { get; set; }
        public string actRoad { get; set; }
        public System.DateTime actTime { get; set; }
        public string actTopic { get; set; }
        public short ageRestrict { get; set; }
        public int clickTimes { get; set; }
        public string hostId { get; set; }
        public bool keepAct { get; set; }
        public string memNick { get; set; }
        public string payment { get; set; }
        public int PeoRestriction { get; set; }
        public string hashTag { get; set; }
        public short genderSerial { get; set; }
        public short serial { get; set; }
        public short BudgetNo { get; set; }
        public short CountyNo { get; set; }
        public short peoSerial { get; set; }
        public short paymentSerial { get; set; }
        public short memCounty { get; set; }
        public short memDistrict { get; set; }
        public string Sex { get; set; }
    }
}
